name: Deploy Spring Boot to EC2

on:
  push:
    branches: [ main ]

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package

      - name: Get artifact name
        id: get-artifact
        run: echo "JAR_FILE=$(ls target/*.jar | head -n 1)" >> $GITHUB_OUTPUT

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ec2-user/app/"
          strip_components: 1

      - name: Rename and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            rm -f myapp.jar
            mv *.jar myapp.jar
            sudo systemctl restart springboot
            sudo systemctl status springboot